- name: generate github-contribution-grid-snake.svg
  uses: platane/snk/svg-only@v3
  with:
    github_user_name: ${{ github.repository_owner }}
    outputs: |
      dist/github-contribution-grid-snake.svg
      dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=deeppink
  env:
    # O primeiro código (#161b22) garante o fundo cinza-azulado que você quer!
    SNK_PALETTE_GITHUB_DARK: "#161b22,#ffb6c1,#ff69b4,#ff1493,#c71585"
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}